### ISSUE TITLE
hw3: when to produce `performance.txt`

### ISSUE THREAD

**Issue by qwe854896** [yungyuc/nsdhw_23sp#79]
Notes on grading mentioned that we need to compare two multiplication functions, and output `performance.txt`.
But the `benchmark()` will also produce a file with the same name.
I think we need to put the result of `multiply_tile` in?
But I don't know when to compare them so that the output file won't be cleared by `benchmark()`.

Or we don't need to hard-code the comparison?
Just upload it to GitHub?

**Comment by yungyuc** [comment]
You may rely on `benchmark()`, but your own timing code is a useful thing during development.  Having it overridden by `benchmark()` shouldn't be a problem because you are unlikely to run the validation script during development.

**Comment by yungyuc** [comment]
It's a bit hard for the CI to check for runtime number, especially when I do not prescribe the format.  Grader will :)
