### ISSUE TITLE
hw1: `countline.py` might not be compatible with `validate.sh`

### ISSUE THREAD

**Issue by qwe854896** [yungyuc/nsdhw_23sp#9]
- Orginal `countline.py` will also count empty lines
- But the result of `validate.sh` does not count empty lines

**Comment by qwe854896** [comment]
I think I am wrong, sorry for bothering

**Comment by yungyuc** [comment]
No problem at all.  File an issue when you cannot figure it out yourself after one hour.

**Comment by qwe854896** [comment]
**Original `countline.py` will not be compatible with `validate.sh`.**

I think I address the problem now.
The problem comes from that `wc -l` only counts the number of `'\n'`, but `python readlines()` will get the list for each lines no matter it's end by `'\n'` or `EOF`.
If your file ends without `'\n'`, the counts will be smaller than the actual number by 1.
BTW, I prefer the answer calculated by python.

For example,
I have two files `test` and `testWithEndline`, and both of them contains one line of content.
The difference between them is that `testWithEndline` has `'\n'` after the content but the other doesn't.

```sh
$ env PYTHON_BIN=python3 ./countline.py test
['test']
1 lines in test
$ env PYTHON_BIN=python3 ./countline.py testWithEndline
['test\n']
1 lines in testWithEndline
$ wc -l test
0 test
$ wc -l testWithEndline 
1 testWithEndline
```

**Comment by yungyuc** [comment]
This depends on how you change `countline.py` and you may use the format that `validate.sh` accepts.  Do you think you can do that?

**Comment by yungyuc** [comment]
@qwe854896 Any comments?

**Comment by qwe854896** [comment]
> This depends on how you change `countline.py` and you may use the format that `validate.sh` accepts.  Do you think you can do that?

Yes, I have done that.
BTW, so the homework allows us to fitting the answer in `validate.sh`?
I think it's a little weird so I send this issue.

**Comment by yungyuc** [comment]
> so the homework allows us to fitting the answer in `validate.sh`? I think it's a little weird so I send this issue.

Correct.  Treat `validate.sh` as a form of regression test.  A regression test does not need to be "right".  It's referred to as "golden" (or sometimes "silver"), because it is the "golden standard" followup results to compare with.

A golden standard is not necessarily a right answer.
